#!/usr/bin/env bash
# shellcheck disable=SC2155

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi

PATH=$PATH:/usr/local/sbin

# export PATH=$HOME/torch/install/bin:$PATH  # Added automatically by torch-dist
# export LD_LIBRARY_PATH=$HOME/torch/install/lib:$LD_LIBRARY_PATH  # Added automatically by torch-dist
# export DYLD_LIBRARY_PATH=$HOME/torch/install/lib:$DYLD_LIBRARY_PATH  # Added automatically by torch-dist

# GOPATH environment variable is used to specify directories outside of $GOROOT
# that contain the source for Go projects and their binaries.
export GOPATH=$HOME/go

export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export PATH=$PATH:/usr/local/go/bin

# Android
export PATH=$PATH:~/android-sdks/tools/:~/android-sdks/platform-tools/

# CUDA
# export PATH=$PATH:/usr/local/cuda/bin
# export CUDA_HOME=/usr/local/cuda
# export LD_LIBRARY_PATH=${CUDA_HOME}/lib64

# CLion
export PATH=$PATH:$HOME/clion/bin

export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/yasara
export PATH=$PATH:$HOME/.cabal/bin:$HOME/.ghcup/bin

# Android development
export PATH=$ANT_HOME/bin:$PATH
export PATH=$MAVEN_HOME/bin:$PATH
export PATH=$GRADLE_HOME/bin:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/build-tools/19.1.0:$PATH

# LLVM (macOS)
if [[ "$unamestr" == 'Darwin' ]]; then
    export PATH="$(brew --prefix llvm)/bin:$PATH"
fi

# Haskell Stack global executables
export PATH=~/.local/bin:$PATH

# Ruby GEMs
GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export GEM_HOME

export PATH="$PATH:$(npm --prefix $HOME/tmp get prefix)/bin:$GEM_HOME/bin"

# npm global packages
# TODO: Move .npm-global_packages to constant
export PATH=~/.npm-global_packages/bin:$PATH
