#!/usr/bin/env bash
# shellcheck disable=SC2155

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
	PATH="$HOME/bin:$PATH"
fi

PATH=$PATH:/usr/local/sbin

# export PATH=$HOME/torch/install/bin:$PATH  # Added automatically by torch-dist
# export LD_LIBRARY_PATH=$HOME/torch/install/lib:$LD_LIBRARY_PATH  # Added automatically by torch-dist
# export DYLD_LIBRARY_PATH=$HOME/torch/install/lib:$DYLD_LIBRARY_PATH  # Added automatically by torch-dist

# GOPATH environment variable is used to specify directories outside of $GOROOT
# that contain the source for Go projects and their binaries.
export GOPATH=$HOME/go

export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/go/bin

# Android
export PATH=$PATH:~/android-sdks/tools/:~/android-sdks/platform-tools/

# CLion
export PATH=$PATH:$HOME/clion/bin

export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/yasara
export PATH=$PATH:$HOME/.cabal/bin:$HOME/.ghcup/bin

# Android development
export PATH=$ANT_HOME/bin:$PATH
export PATH=$MAVEN_HOME/bin:$PATH
export PATH=$GRADLE_HOME/bin:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/build-tools/19.1.0:$PATH

# GNU coreutils
if [[ "$(uname)" == "Darwin" ]]; then
	export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
	export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
fi

# Haskell Stack global executables
export PATH=~/.local/bin:$PATH

# LLVM (macOS only)
if [[ "$(uname)" == "Darwin" ]]; then
	export PATH="$(brew --prefix llvm)/bin:$PATH"
fi

# Ruby GEMs
if command -v ruby >/dev/null 2>&1; then
	GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
	export GEM_HOME
fi

if command -v ruby >/dev/null 2>&1; then
	export PATH="$PATH:$(npm --prefix "$HOME"/tmp get prefix)/bin:$GEM_HOME/bin"
fi

# npm global packages
export NPM_GLOBAL_PACKAGES_DIRECTORY="$HOME"/.npm-global_packages

export PATH="$NPM_GLOBAL_PACKAGES_DIRECTORY"/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
